title: dieudv
subtitle: Indie Hacker
description: >- # this means to ignore newlines until "baseurl:"
  sometime i like to code, sometime i like to write.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: Projects
      url : /projects
    # - text: Gallery
      # url: /gallery
    - text: About
      url: /about
    # - text: Contact
      # url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Dieu
author_bio: Hi, I'm Dieu. I'm an indie hacker :D
author_email: "dieu.dv@hotmail.com"
author_location: Vietnam
author_website_url: "https://dieudv.github.io"
typewrite-text: sometime i like to code, sometime i like to write.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: dieudv.github.io
              company_logo: indie-hacker.png
              company_url: https://dieudv.github.io
              designation: Indie Hacker
              description: Working on my products :)
              visibility: true
            - company_name: AI Labs Makerspace
              company_logo: aifablab.jpg
              company_url: https://www.facebook.com/aifablab/
              designation: Full-stack Developer
              description: Worked on STEAM products
              visibility: true
            - company_name: Gameloft
              company_logo: gameloft.webp
              company_url: https://gameloft.com
              designation: Programmer
              description: Worked on game projects
              visibility: true

# Education
author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: proj/f13-tools.png
                project_title: F13 Tools Extension
                project_description: Bộ công cụ tự động dành cho FB cá nhân
                project_url: https://lzdev.org/f13-tools
                visibility: true
              - project_thumbnail: proj/melouni.png
                project_title: Melouni
                project_description: Trang web nghe nhạc chung cùng bạn bè
                project_url: https://melouni.com
                visibility: true
              - project_thumbnail: proj/tinker.png
                project_title: Tinker Browser
                project_description: Trình duyệt tinh chỉnh cho android
                project_url: https://play.google.com/store/apps/details?id=tinker.browser
                visibility: true
              - project_thumbnail: proj/vpn4g.webp
                project_title: VNP 4G
                project_description: Ứng dụng truy cập 4G free cho android
                project_url: https://play.google.com/store/apps/details?id=vn.vpn4g
                visibility: true
              - project_thumbnail: proj/trueordare.png
                project_title: Truth Or Dare
                project_description: Trò chơi thật hay thách trên android
                project_url: https://play.google.com/store/apps/details?id=com.truthordare.challenge
                visibility: true
              - project_thumbnail: proj/oldtv.png
                project_title: Old TV
                project_description: TV Launcher cho tivi box kết hợp với tivi đời cũ (open source)
                project_url: https://github.com/dieudv/oldtv
                visibility: true
              - project_thumbnail: proj/codi.png
                project_title: Codi - Code your device
                project_description: Lập trình thiết bị của bạn với việc kéo thả
                project_url: https://play.google.com/store/apps/details?id=com.codi.utils
                visibility: true
              - project_thumbnail: proj/pkglist.png
                project_title: Package Name Viewer
                project_description: Xem và quản lý package name trên android
                project_url: https://play.google.com/store/apps/details?id=com.pkglist
                visibility: true
              - project_thumbnail: proj/matthuonline.png
                project_title: Mật Thư Online
                project_description: Trò chơi giải mật thư online dành cho những bạn đam mê mật thư
                project_url: https://play.google.com/store/apps/details?id=dieuk.matthuonline
                visibility: true
              - project_thumbnail: proj/semoplay.png
                project_title: Semaphore & Morse Trainer
                project_description: Luyện tập semaphore & morse trên android
                project_url: https://play.google.com/store/apps/details?id=dieuk.semoplay
                visibility: true
              - project_thumbnail: proj/matthu.png
                project_title: Giải Mã Mật Thư
                project_description: Phần mềm chuyên giải mật thư cho android
                project_url: https://play.google.com/store/apps/details?id=dieuk.gmmt
                visibility: true
              - project_thumbnail: proj/semaphore.png
                project_title: Semaphore Translate
                project_description: Nhận diện semaphore bằng camera sử dụng AI
                project_url: https://play.google.com/store/apps/details?id=com.semaphore.translate
                visibility: true
              - project_thumbnail: proj/matthu.png
                project_title: Matthu.vn
                project_description: Trang web chuyên về mật thư
                project_url: https://matthu.vn
                visibility: true

# social links
twitter_username: dieudv
github_username:  dieudv
facebook_username: dieudv
linkedin_username: dieudv
# behance_username: dieudv
# instagram_username: dieudv
# medium_username: dieudv
telegram_username: dieudv
# dribbble_username: dieudv
# flickr_username: dieudv

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: dieu.dv@hotmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 8
per_page: 8
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
